### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [mk-fg/acme-cert-tool#4]
### Description:

In the "acme-cert-tool/acme-cert-tool.py", I have identified a security vulnerability about insecure cryptographic algorithm. PKCS1v1.5  is vulnerable to the chosen-ciphertext attack.

### Location:

https://github.com/mk-fg/acme-cert-tool/blob/master/acme-cert-tool.py#L171

```python
padding=padding.PKCS1v15(), algorithm=hashes.SHA256()
```

### Reference

- **CWE-780: Use of RSA Algorithm without OAEP**

### Recommendations:

Try using other padding(OAEP) instead of PKCS1v1.5.

**Comment by mk-fg** [comment]
As mentioned in the comment within the linked code, this is limited by https://datatracker.ietf.org/doc/html/rfc7518#section-3.1 , OAEP is not an option there, and PKCS#1 1.5 is still recommended.
RSASSA-PSS might be, and I don't remember whether I've tested it with LE, and whether it was available at the time of the implementation, but yeah, might be an option.

Afaict specific CWE-780 has nothing to do with PKCS#1 1.5, and is about using RSA without padding for encryption purposes, which is not the case here, and idk if there's any problem with using PKCS#1 1.5 for signing.
I think at this point, it might also make more sense to drop RSA entirely in favor of EC-only keys/certs (which were always the default here), since afaik they're supported everywhere.

This particular issue seem to be an automated spam across many repos though, so probably not really worth replying to, but thought to write down my thoughts/understanding on that padding usage anyway, in case someone else might stumble upon it later.
